Private admin route
klim9d61/endava-portal pull request #25
Opened 2019-12-19 12:50 UTC by mirabela-t

## Changelog

```changelog
- Add admin private route
- Add 403 & 404 pages
```

## Change Type

- [x] `Added`: new feature - non-breaking change which adds functionality.
- [x] `Bug fix`: non-breaking change which fixes an issue.
- [x] `Changed`: for changes in existing functionality.
- [ ] `Deprecated`: for soon-to-be removed features.
- [ ] `Documentation` update.
- [ ] `Performance`: for performance and optimization functionality.
- [ ] `Removed`: for now removed features.
- [ ] `Security`: in case of vulnerabilities.

## Required Checks

- [ ] Documentation
- [ ] Unit tests
- [x] Tested on Chrome
- [x] Tested on Firefox
- [x] Tested on IE11
- [x] npm run eslint
- [x] npm run prettier

## Screenshots

---

2019-12-19 13:41 UTC, calcutinE commented on src/pages/notAuthorized/index.js
> +        style={{ zoom: '1.1' }}
whats the purpose of zoom here? why not setting the correct values for width & height of elements?

2019-12-19 13:43 UTC, calcutinE requested changes
Please get rid of `zoom` since there is no pros & benefits for using that.

2019-12-19 13:51 UTC, ekalkutin approved these changes

2019-12-20 09:36 UTC, utopiaeh approved these changes

2019-12-20 09:56 UTC, CapceleaCristian approved these changes

2019-12-20 10:36 UTC, UncleFairy approved these changes

2019-12-20 10:37 UTC, merged