Add user role access features
klim9d61/endava-portal pull request #26
Opened 2019-12-19 12:54 UTC by UncleFairy

## Changelog

```changelog
 - Endava Portal: Add user role access features
```

## Change Type

- [ ] `Added`: new feature - non-breaking change which adds functionality.
- [ ] `Bug fix`: non-breaking change which fixes an issue.
- [ ] `Changed`: for changes in existing functionality.
- [ ] `Deprecated`: for soon-to-be removed features.
- [ ] `Documentation` update.
- [ ] `Performance`: for performance and optimization functionality.
- [ ] `Removed`: for now removed features.
- [ ] `Security`: in case of vulnerabilities.

## Required Checks

- [ ] Documentation
- [ ] Unit tests
- [ ] Tested on Chrome
- [ ] Tested on Firefox
- [ ] Tested on IE11
- [ ] npm run eslint
- [ ] npm run prettier

## Screenshots

---

2019-12-19 13:49 UTC, ekalkutin requested changes

2019-12-19 13:49 UTC, ecalcutin commented on src/common/utils.js
> +  JSON.parse(window.localStorage.getItem('currentUser'))[type]
If localStorage have not `currentUser` then you get uncaught exception like `Cannot read property type of undefined`. Fix that in advance

2019-12-20 09:36 UTC, utopiaeh approved these changes

2019-12-20 10:09 UTC, CapceleaCristian approved these changes

2019-12-20 10:22 UTC, andreiturcanu approved these changes

2019-12-20 10:22 UTC, andreiturcanu commented on src/common/utils.js
> +    roleAccessLevel >= accessLevel ? (
You could use here logical && operator and then ternary, to avoid nesting ternary and esLint doesn't complain

2019-12-20 10:33 UTC, mirabela-t approved these changes

2019-12-20 10:35 UTC, merged